version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: db_quanto_ta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
